/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/ai/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate an explanation over verified findings */
        post: operations["explain_api_v1_ai_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a human-readable AI summary of the analysis */
        post: operations["summarize_api_v1_ai_summarize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analyzers, stages, and limits in this build */
        get: operations["capabilities_api_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a URL for analysis */
        post: operations["create_scan_api_v1_scans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan status and stage progress */
        get: operations["get_scan_api_v1_scans__scan_id__get"];
        put?: never;
        post?: never;
        /**
         * Release the server-side copy of a scan
         * @description Called by the client once the result is stored in IndexedDB.
         *
         *     Idempotent: an unknown id also returns 204, because the desired end state - no server copy -
         *     holds either way.
         */
        delete: operations["delete_scan_api_v1_scans__scan_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server-sent events for scan progress */
        get: operations["scan_events_api_v1_scans__scan_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Structured analysis result */
        get: operations["get_result_api_v1_scans__scan_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness and browser readiness
         * @description Report service liveness and whether a browser is available.
         *
         *     ``status`` stays ``ok`` when the browser is missing: the API is up and HTTP-only scans still
         *     work. The frontend uses ``browser.available`` to warn before a scan instead of after.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisResult */
        AnalysisResult: {
            /** Errors */
            errors?: components["schemas"]["ScanError"][];
            /** Limitations */
            limitations?: string[];
            scan: components["schemas"]["ScanMetadata"];
            /**
             * Schema Version
             * @default 2.0
             */
            schema_version: string;
            /** Screenshots */
            screenshots?: components["schemas"]["ScreenshotRef"][];
            sections: components["schemas"]["SectionSet"];
            target: components["schemas"]["TargetInfo"];
        };
        /** AnalyzerCapability */
        AnalyzerCapability: {
            /** Depends On */
            depends_on: string[];
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Implemented */
            implemented: boolean;
            /** Planned Phase */
            planned_phase: number;
            /** Requires */
            requires: string[];
            section: components["schemas"]["SectionKey"];
            /** Version */
            version: string;
        };
        /**
         * AnalyzerRun
         * @description Outcome of one analyzer within one scan. Present even when it did not run.
         */
        AnalyzerRun: {
            /** Duration Ms */
            duration_ms?: number | null;
            error_code?: components["schemas"]["ErrorCode"] | null;
            /** Error Detail */
            error_detail?: string | null;
            /** Id */
            id: string;
            /** Missing Evidence */
            missing_evidence?: string[];
            status: components["schemas"]["AnalyzerRunStatus"];
            /** Version */
            version: string;
        };
        /**
         * AnalyzerRunStatus
         * @enum {string}
         */
        AnalyzerRunStatus: "completed" | "failed" | "skipped" | "timeout" | "not_implemented";
        /**
         * AppliedCap
         * @description A band ceiling triggered by a dominant observation.
         */
        AppliedCap: {
            cap: components["schemas"]["PostureBand"];
            /** Reason */
            reason: string;
            /** Rule Id */
            rule_id: string;
        };
        /** AxeNode */
        AxeNode: {
            /** Failure Summary */
            failure_summary?: string | null;
            /** Html Excerpt */
            html_excerpt?: string | null;
            /** Target */
            target?: string[];
        };
        /**
         * AxeObservation
         * @description Results from the vendored, pinned axe-core build.
         *
         *     ``engine_version`` is recorded because rule sets change between versions, so a stored
         *     result is only interpretable against the engine that produced it.
         */
        AxeObservation: {
            /**
             * Engine Name
             * @default axe-core
             */
            engine_name: string;
            /** Engine Version */
            engine_version: string;
            /** Error */
            error?: string | null;
            /** Inapplicable Count */
            inapplicable_count?: number | null;
            /** Incomplete Count */
            incomplete_count?: number | null;
            /** Passes Count */
            passes_count?: number | null;
            /** Rules Run Count */
            rules_run_count?: number | null;
            /** Violations */
            violations?: components["schemas"]["AxeViolation"][];
        };
        /** AxeViolation */
        AxeViolation: {
            /** Description */
            description: string;
            /** Help Text */
            help_text: string;
            /** Help Url */
            help_url?: string | null;
            /** Impact */
            impact?: string | null;
            /** Node Count */
            node_count: number;
            /** Rule Id */
            rule_id: string;
            /** Sample Nodes */
            sample_nodes?: components["schemas"]["AxeNode"][];
            /** Tags */
            tags?: string[];
        };
        /** BrowserHealth */
        BrowserHealth: {
            /** Available */
            available: boolean;
            /** Detail */
            detail?: string | null;
            /** Name */
            name?: string | null;
            /** Version */
            version?: string | null;
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            /** Analyzers */
            analyzers: components["schemas"]["AnalyzerCapability"][];
            /** Collection Mode */
            collection_mode: string;
            /** Engine Version */
            engine_version: string;
            /** Inference Available */
            inference_available: boolean;
            limits: components["schemas"]["ScanLimits"];
            /** Research Available */
            research_available: boolean;
            /** Schema Version */
            schema_version: string;
            /** Sections */
            sections: components["schemas"]["SectionKey"][];
            /** Stages */
            stages: components["schemas"]["StageCapability"][];
            /** Traffic Provider Available */
            traffic_provider_available: boolean;
        };
        /**
         * Confidence
         * @description Internal reasoning metadata.
         *
         *     Used only to derive :class:`FindingStatus`. Never rendered next to a claim: a
         *     percentage or grade beside an uncertain statement reads as authority and launders a
         *     guess into a fact.
         * @enum {string}
         */
        Confidence: "definitive" | "strong" | "moderate" | "weak";
        /**
         * DesignPayload
         * @description Recreation-oriented design data. coverage reports sample quality.
         */
        DesignPayload: {
            axe?: components["schemas"]["AxeObservation"] | null;
            coverage?: components["schemas"]["SampleCoverage"] | null;
        };
        /**
         * DetectedProduct
         * @description A technology detected from observable signals.
         */
        DetectedProduct: {
            /** Categories */
            categories?: string[];
            /** Finding Id */
            finding_id: string;
            /** Name */
            name: string;
            /**
             * Signal Summary
             * @description Human-readable list of the signals that matched.
             */
            signal_summary?: string[];
            status: components["schemas"]["FindingStatus"];
            /**
             * Version
             * @description Only set when a signature captured a version explicitly.
             */
            version?: string | null;
        };
        /** DomainSummary */
        DomainSummary: {
            /** Host */
            host: string;
            /** Is Third Party */
            is_third_party: boolean;
            /** Request Count */
            request_count: number;
            /** Transfer Bytes */
            transfer_bytes?: number | null;
        };
        /** DroppedClaim */
        DroppedClaim: {
            /** Reason */
            reason: string;
            /** Text */
            text: string;
        };
        /**
         * ErrorCode
         * @description Machine-readable error identity, shared by problem responses and scan errors.
         * @enum {string}
         */
        ErrorCode: "INVALID_REQUEST" | "INVALID_URL" | "BLOCKED_TARGET" | "ROBOTS_DISALLOWED" | "DNS_FAILURE" | "CONNECT_FAILURE" | "TLS_FAILURE" | "NAVIGATION_TIMEOUT" | "BROWSER_UNAVAILABLE" | "ACCESS_RESTRICTED" | "BUDGET_EXHAUSTED" | "MISSING_EVIDENCE" | "ANALYZER_FAILED" | "ANALYZER_TIMEOUT" | "SCAN_NOT_FOUND" | "RESULT_EXPIRED" | "SCAN_IN_PROGRESS" | "RATE_LIMITED" | "AI_DISABLED" | "INTERNAL_ERROR";
        /**
         * EvidenceKind
         * @description What kind of observation an :class:`~weblens.domain.evidence.EvidenceRef` points at.
         * @enum {string}
         */
        EvidenceKind: "http_header" | "http_status" | "redirect_hop" | "html_element" | "html_attribute" | "meta_tag" | "inline_script" | "script_url" | "stylesheet_url" | "runtime_global" | "computed_style" | "loaded_font" | "cookie" | "tls_connection" | "dns_record" | "robots_directive" | "network_request" | "performance_entry" | "axe_result" | "console_message" | "dom_measurement" | "research_source" | "ai_reasoning";
        /**
         * EvidenceRef
         * @description A pointer to the observation that supports a finding, with a quotable excerpt.
         *
         *     Deliberately self-contained rather than an index into a separate evidence store:
         *     findings travel alone into report files and IndexedDB, so each carries the bounded,
         *     sanitized excerpt it needs. ``RawEvidence`` itself is never returned by the API.
         */
        EvidenceRef: {
            /** Detail */
            detail?: {
                [key: string]: string | number | boolean | null;
            };
            /**
             * Excerpt
             * @description Sanitized, truncated raw value as observed.
             */
            excerpt?: string | null;
            kind: components["schemas"]["EvidenceKind"];
            /**
             * Location
             * @description Absolute URL, CSS selector, or header name.
             */
            location?: string | null;
            /**
             * Source
             * @description Machine path into the evidence, e.g. 'http.headers.content-security-policy'.
             */
            source: string;
        };
        /** ExcludedRule */
        ExcludedRule: {
            /** Id */
            id: string;
            /** @description Either not_applicable or unknown. */
            outcome: components["schemas"]["RuleOutcome"];
            /** Reason */
            reason: string;
        };
        /** ExplainRequest */
        ExplainRequest: {
            /**
             * Audience
             * @default engineer
             */
            audience: string;
            /** Scan Id */
            scan_id: string;
            /** Sections */
            sections?: components["schemas"]["SectionKey"][] | null;
        };
        /** ExplainResponse */
        ExplainResponse: {
            /**
             * Dropped Claims
             * @description Statements removed because they could not be traced to a finding.
             */
            dropped_claims?: components["schemas"]["DroppedClaim"][];
            /** Generated At */
            generated_at: string;
            /** Model */
            model?: string | null;
            /** Narratives */
            narratives?: components["schemas"]["Narrative"][];
            /** Provider */
            provider: string;
            /** Scan Id */
            scan_id: string;
        };
        /**
         * Finding
         * @description One structured conclusion about one property of the target.
         */
        Finding: {
            /**
             * Category
             * @description Grouping within the section, e.g. 'response_headers'.
             */
            category: string;
            /** @description Internal reasoning metadata used to derive status. Not a user-facing qualifier - see docs/blueprint/decisions.md D5. */
            confidence?: components["schemas"]["Confidence"] | null;
            /** Details */
            details?: {
                [key: string]: string | number | boolean | string[] | null;
            };
            /**
             * Detected
             * @description None when the notion of detection does not apply.
             */
            detected?: boolean | null;
            /** Evidence */
            evidence?: components["schemas"]["EvidenceRef"][];
            /**
             * Id
             * @description '<analyzer_id>:<slug>', unique within a result.
             */
            id: string;
            /** Limitations */
            limitations?: string[];
            /**
             * Name
             * @description Human-readable label.
             */
            name: string;
            /**
             * Reason
             * @description Required for every negative status: why not.
             */
            reason?: string | null;
            /**
             * Source
             * @description Id of the analyzer that produced this finding.
             */
            source: string;
            status: components["schemas"]["FindingStatus"];
            /**
             * Unit
             * @description 'ms', 'bytes', 'px', '%', 'days'.
             */
            unit?: string | null;
            /** Value */
            value?: string | number | boolean | null;
            /** Values */
            values?: string[];
        };
        /**
         * FindingStatus
         * @description User-facing certainty of a finding.
         *
         *     The negative states are deliberately distinct: they answer different questions
         *     and conflating them is how a tool starts making things up.
         * @enum {string}
         */
        FindingStatus: "verified" | "strongly_inferred" | "inferred" | "ai_inferred" | "not_detected" | "not_determinable" | "unable_to_verify";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HeaderEntry
         * @description One response header. Duplicates are preserved as separate entries.
         *
         *     Collapsing duplicate headers loses information that matters (multiple ``Set-Cookie``
         *     lines, repeated ``Content-Security-Policy``), so the list keeps them intact.
         */
        HeaderEntry: {
            /** Name */
            name: string;
            /** Value */
            value: string;
        };
        /** HeaderObservationSummary */
        HeaderObservationSummary: {
            /** Name */
            name: string;
            /** Present */
            present: boolean;
            /** Value */
            value?: string | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Active Scans */
            active_scans: number;
            browser: components["schemas"]["BrowserHealth"];
            /** Engine Version */
            engine_version: string;
            /** Schema Version */
            schema_version: string;
            /** Status */
            status: string;
            /** Uptime Seconds */
            uptime_seconds: number;
        };
        /** HreflangEntry */
        HreflangEntry: {
            /** Href */
            href?: string | null;
            /** Hreflang */
            hreflang: string;
        };
        /** IndexabilityObservation */
        IndexabilityObservation: {
            /** Canonical Is Self Referential */
            canonical_is_self_referential?: boolean | null;
            /** Redirect Hop Count */
            redirect_hop_count?: number | null;
            /** Robots Txt Allowed */
            robots_txt_allowed?: boolean | null;
            /** Sitemaps */
            sitemaps?: string[];
            /** X Robots Tag */
            x_robots_tag?: string | null;
        };
        /**
         * Interpretation
         * @description A subjective statement derived from findings, kept structurally separate from them.
         *
         *     Interpretations cannot be built without citing findings, and only analyzers whose job
         *     is interpretation emit them. That is how "observed fact" and "our reading of it" stay
         *     apart in the API, the UI, and every generated report.
         */
        Interpretation: {
            /**
             * Basis
             * @description Finding ids this reading is derived from.
             */
            basis: string[];
            /**
             * Caveat
             * @default Interpretation derived from observed values, not a directly observed fact.
             */
            caveat: string;
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Statement */
            statement: string;
        };
        /** KeyValueObservation */
        KeyValueObservation: {
            /** Key */
            key: string;
            /** Value */
            value?: string | null;
        };
        /** LongTaskEntry */
        LongTaskEntry: {
            /** Duration Ms */
            duration_ms: number;
            /** Start Ms */
            start_ms: number;
        };
        /**
         * MetadataObservation
         * @description Document metadata as served. Lengths are reported because they are actionable.
         */
        MetadataObservation: {
            /** Canonical */
            canonical?: string | null;
            /** Charset */
            charset?: string | null;
            /** Description */
            description?: string | null;
            /** Description Length */
            description_length?: number | null;
            /** Favicons */
            favicons?: string[];
            /** H1 Texts */
            h1_texts?: string[];
            /** Hreflang */
            hreflang?: components["schemas"]["HreflangEntry"][];
            /** Lang */
            lang?: string | null;
            /** Open Graph */
            open_graph?: components["schemas"]["KeyValueObservation"][];
            /** Robots Meta */
            robots_meta?: string | null;
            /** Title */
            title?: string | null;
            /** Title Length */
            title_length?: number | null;
            /** Twitter */
            twitter?: components["schemas"]["KeyValueObservation"][];
            /** Viewport Meta */
            viewport_meta?: string | null;
        };
        /** Narrative */
        Narrative: {
            /**
             * Grounded In
             * @description Finding ids the text cites. Every sentence must cite at least one.
             */
            grounded_in: string[];
            section: components["schemas"]["SectionKey"];
            /** Text */
            text: string;
        };
        /**
         * NetworkRequestRecord
         * @description One request/response pair observed during navigation.
         *
         *     ``Set-Cookie`` values and authorization headers are never captured; only the selected
         *     cache/CORS/security headers listed by the collector reach this record.
         */
        NetworkRequestRecord: {
            /** Decoded Bytes */
            decoded_bytes?: number | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /**
             * Failed
             * @default false
             */
            failed: boolean;
            /** Failure Text */
            failure_text?: string | null;
            /** From Cache */
            from_cache?: boolean | null;
            /** Host */
            host?: string | null;
            /** Initiator Type */
            initiator_type?: string | null;
            /** Is Same Origin */
            is_same_origin?: boolean | null;
            /** Is Same Site */
            is_same_site?: boolean | null;
            /** Method */
            method: string;
            /** Mime Type */
            mime_type?: string | null;
            /** Protocol */
            protocol?: string | null;
            /** Resource Type */
            resource_type: string;
            /** Selected Headers */
            selected_headers?: components["schemas"]["HeaderEntry"][];
            /**
             * Sets Cookie
             * @default false
             */
            sets_cookie: boolean;
            /** Status */
            status?: number | null;
            /** Transfer Bytes */
            transfer_bytes?: number | null;
            /** Url */
            url: string;
        };
        /**
         * PerformanceObservation
         * @description Single cold lab run at a bounded settle point. Not field data (see L-PERF-01).
         */
        PerformanceObservation: {
            /** Cumulative Layout Shift */
            cumulative_layout_shift?: number | null;
            /** Decoded Bytes Total */
            decoded_bytes_total?: number | null;
            /** Dom Content Loaded Ms */
            dom_content_loaded_ms?: number | null;
            /** Dom Interactive Ms */
            dom_interactive_ms?: number | null;
            /** First Contentful Paint Ms */
            first_contentful_paint_ms?: number | null;
            /** Largest Contentful Paint Element */
            largest_contentful_paint_element?: string | null;
            /** Largest Contentful Paint Ms */
            largest_contentful_paint_ms?: number | null;
            /** Load Event Ms */
            load_event_ms?: number | null;
            /** Long Tasks */
            long_tasks?: components["schemas"]["LongTaskEntry"][];
            /** Render Blocking Request Count */
            render_blocking_request_count?: number | null;
            /** Request Count */
            request_count?: number | null;
            /** Total Blocking Estimate Ms */
            total_blocking_estimate_ms?: number | null;
            /** Transfer Bytes Total */
            transfer_bytes_total?: number | null;
            /** Ttfb Ms */
            ttfb_ms?: number | null;
        };
        /**
         * PostureBand
         * @description Descriptive bands. Never 'secure'/'insecure' - see docs/blueprint/11.
         * @enum {string}
         */
        PostureBand: "strong" | "good" | "moderate" | "limited" | "minimal";
        /**
         * ProblemDetail
         * @description RFC 9457 problem document.
         */
        ProblemDetail: {
            code: components["schemas"]["ErrorCode"];
            /** Detail */
            detail?: string | null;
            /** Instance */
            instance?: string | null;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /**
             * Type
             * @description Stable URI identifying the problem kind.
             */
            type: string;
        };
        /** RedirectHop */
        RedirectHop: {
            /** Location */
            location?: string | null;
            /** Scheme */
            scheme: string;
            /** Status */
            status: number;
            /** Url */
            url: string;
        };
        /** RobotsObservation */
        RobotsObservation: {
            /** Allowed */
            allowed?: boolean | null;
            /** Error */
            error?: string | null;
            /** Fetched */
            fetched: boolean;
            /** Matched Directive */
            matched_directive?: string | null;
            /** Sitemaps */
            sitemaps?: string[];
            /** Status */
            status?: number | null;
            /** Url */
            url: string;
            /** User Agent Group */
            user_agent_group?: string | null;
        };
        /**
         * RuleOutcome
         * @description Outcome of one security scoring rule.
         * @enum {string}
         */
        RuleOutcome: "pass" | "partial" | "fail" | "not_applicable" | "unknown";
        /**
         * RunContext
         * @description The conditions the measurements were taken under.
         *
         *     Performance and design numbers are meaningless without this, so it travels with every
         *     result and is printed in every report.
         */
        RunContext: {
            /** Browser Name */
            browser_name?: string | null;
            /** Browser Version */
            browser_version?: string | null;
            /**
             * Collection Mode
             * @description 'http_only' or 'browser'. Tells the reader which evidence base was used.
             */
            collection_mode: string;
            /**
             * Cpu Throttling
             * @default none
             */
            cpu_throttling: string;
            /**
             * Device Scale Factor
             * @default 1
             */
            device_scale_factor: number;
            /**
             * Locale
             * @default en-US
             */
            locale: string;
            /**
             * Network Throttling
             * @default none
             */
            network_throttling: string;
            /** Settle Reached */
            settle_reached?: boolean | null;
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
            /**
             * User Agent
             * @default WebLens/0.1.0 (+https://github.com/weblens; passive website analyzer; respects robots.txt)
             */
            user_agent: string;
            viewport?: components["schemas"]["Viewport"];
            /**
             * Wait Strategy
             * @description e.g. 'domcontentloaded+network_idle(5000ms)'.
             */
            wait_strategy: string;
        };
        /**
         * SampleCoverage
         * @description How much of the page the style sample actually covers.
         *
         *     Reported alongside every design finding: a claim about "the" border radius of a page
         *     means little without knowing it came from 1500 of 40000 elements.
         */
        SampleCoverage: {
            /**
             * Cap Hit
             * @default false
             */
            cap_hit: boolean;
            /** Elements Sampled */
            elements_sampled: number;
            /** Elements Total */
            elements_total?: number | null;
        };
        /** ScanAcceptedResponse */
        ScanAcceptedResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Links */
            links: {
                [key: string]: string;
            };
            /** Normalized Url */
            normalized_url: string;
            /** Requested Url */
            requested_url: string;
            /** Scan Id */
            scan_id: string;
            status: components["schemas"]["ScanStatus"];
        };
        /**
         * ScanError
         * @description A failure recorded on a result rather than raised to the caller.
         */
        ScanError: {
            code: components["schemas"]["ErrorCode"];
            /** Detail */
            detail?: string | null;
            /** Message */
            message: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at?: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "scan" | "stage" | "analyzer";
            /**
             * Subject
             * @description Stage key or analyzer id the failure belongs to.
             */
            subject: string;
        };
        /** ScanJobState */
        ScanJobState: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Finished At */
            finished_at?: string | null;
            problem?: components["schemas"]["ProblemDetail"] | null;
            progress?: components["schemas"]["StageProgress"];
            /** Requested Url */
            requested_url: string;
            /** Scan Id */
            scan_id: string;
            /** Stages */
            stages?: components["schemas"]["StageRun"][];
            /** Started At */
            started_at?: string | null;
            status: components["schemas"]["ScanStatus"];
        };
        /** ScanLimits */
        ScanLimits: {
            /** Analyzer Timeout Ms */
            analyzer_timeout_ms: number;
            /** Max Concurrent Scans */
            max_concurrent_scans: number;
            /** Max Concurrent Scans Per Host */
            max_concurrent_scans_per_host: number;
            /** Max Redirects */
            max_redirects: number;
            /** Min Host Interval Seconds */
            min_host_interval_seconds: number;
            /** Navigation Timeout Ms */
            navigation_timeout_ms: number;
            /** Probe Http Downgrade */
            probe_http_downgrade: boolean;
            /** Respect Robots */
            respect_robots: boolean;
            /** Result Ttl Seconds */
            result_ttl_seconds: number;
            /** Total Scan Budget Ms */
            total_scan_budget_ms: number;
        };
        /** ScanMetadata */
        ScanMetadata: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /**
             * Engine Version
             * @default 0.1.0
             */
            engine_version: string;
            /** Finished At */
            finished_at?: string | null;
            options: components["schemas"]["ScanOptions"];
            run_context?: components["schemas"]["RunContext"] | null;
            /** Scan Id */
            scan_id: string;
            /**
             * Schema Version
             * @default 2.0
             */
            schema_version: string;
            /** Stages */
            stages?: components["schemas"]["StageRun"][];
            /** Started At */
            started_at?: string | null;
            status: components["schemas"]["ScanStatus"];
        };
        /**
         * ScanOptions
         * @description Per-scan options. ``extra='forbid'`` so an option typo is a 422, not a silent no-op.
         */
        ScanOptions: {
            /**
             * Include Full Page Screenshot
             * @default false
             */
            include_full_page_screenshot: boolean;
            /**
             * Include Screenshot
             * @default true
             */
            include_screenshot: boolean;
            /** Responsive Widths */
            responsive_widths?: number[];
            /**
             * Sections
             * @description Restrict analysis to these sections. None means all.
             */
            sections?: components["schemas"]["SectionKey"][] | null;
            viewport?: components["schemas"]["Viewport"];
        };
        /** ScanRequest */
        ScanRequest: {
            options?: components["schemas"]["ScanOptions"];
            /**
             * Url
             * @description Public http(s) URL. Normalized and guarded server-side.
             */
            url: string;
        };
        /**
         * ScanStatus
         * @enum {string}
         */
        ScanStatus: "queued" | "running" | "completed" | "completed_with_errors" | "failed" | "cancelled";
        /**
         * ScreenshotRef
         * @description Screenshot metadata plus inline data.
         *
         *     The client moves the bytes into its own IndexedDB store as a Blob and does not keep them
         *     in the result record, which is why this is a separate top-level list rather than being
         *     buried inside the design payload.
         */
        ScreenshotRef: {
            /** Data Base64 */
            data_base64: string;
            /** Height */
            height: number;
            /** Label */
            label: string;
            /**
             * Mime Type
             * @default image/png
             */
            mime_type: string;
            /** Width */
            width: number;
        };
        /**
         * SectionKey
         * @description The four user-facing report sections. Order here is the canonical presentation order.
         *
         *     V2 consolidated eight sections into four. Architecture, network, performance, SEO, and
         *     accessibility evidence still feeds the remaining sections internally but is no longer
         *     exposed as standalone user-facing reports.
         * @enum {string}
         */
        SectionKey: "design" | "technology" | "security" | "traffic";
        /** SectionMeta */
        SectionMeta: {
            /** Analyzers */
            analyzers?: components["schemas"]["AnalyzerRun"][];
            key: components["schemas"]["SectionKey"];
            /** Limitations */
            limitations?: string[];
            status: components["schemas"]["SectionStatus"];
            /** Unavailable Reason */
            unavailable_reason?: string | null;
        };
        /**
         * SectionSet
         * @description The four V2 report sections.
         */
        SectionSet: {
            design: components["schemas"]["Section_DesignPayload_"];
            security: components["schemas"]["Section_SecurityPayload_"];
            technology: components["schemas"]["Section_TechnologyPayload_"];
            traffic: components["schemas"]["Section_TrafficPayload_"];
        };
        /**
         * SectionStatus
         * @enum {string}
         */
        SectionStatus: "complete" | "partial" | "unavailable" | "not_implemented" | "skipped";
        /** Section[DesignPayload] */
        Section_DesignPayload_: {
            data?: components["schemas"]["DesignPayload"] | null;
            /** Findings */
            findings?: components["schemas"]["Finding"][];
            /** Interpretations */
            interpretations?: components["schemas"]["Interpretation"][];
            meta: components["schemas"]["SectionMeta"];
        };
        /** Section[SecurityPayload] */
        Section_SecurityPayload_: {
            data?: components["schemas"]["SecurityPayload"] | null;
            /** Findings */
            findings?: components["schemas"]["Finding"][];
            /** Interpretations */
            interpretations?: components["schemas"]["Interpretation"][];
            meta: components["schemas"]["SectionMeta"];
        };
        /** Section[TechnologyPayload] */
        Section_TechnologyPayload_: {
            data?: components["schemas"]["TechnologyPayload"] | null;
            /** Findings */
            findings?: components["schemas"]["Finding"][];
            /** Interpretations */
            interpretations?: components["schemas"]["Interpretation"][];
            meta: components["schemas"]["SectionMeta"];
        };
        /** Section[TrafficPayload] */
        Section_TrafficPayload_: {
            data?: components["schemas"]["TrafficPayload"] | null;
            /** Findings */
            findings?: components["schemas"]["Finding"][];
            /** Interpretations */
            interpretations?: components["schemas"]["Interpretation"][];
            meta: components["schemas"]["SectionMeta"];
        };
        /**
         * SecurityCategory
         * @enum {string}
         */
        SecurityCategory: "transport" | "headers" | "cookies" | "content_integrity" | "exposure";
        /**
         * SecurityPayload
         * @description ``score`` is the only score in the whole domain model (axiom A4).
         */
        SecurityPayload: {
            /** Headers */
            headers?: components["schemas"]["HeaderObservationSummary"][];
            score?: components["schemas"]["SecurityScore"] | null;
        };
        /** SecurityRuleResult */
        SecurityRuleResult: {
            /**
             * Awarded
             * @description Points earned, between 0 and weight.
             */
            awarded: number;
            category: components["schemas"]["SecurityCategory"];
            /** Evidence */
            evidence?: components["schemas"]["EvidenceRef"][];
            /**
             * Id
             * @description Stable rule id, e.g. 'HDR-01'.
             */
            id: string;
            outcome: components["schemas"]["RuleOutcome"];
            /**
             * Rationale
             * @description Why this outcome, stated in observable terms.
             */
            rationale: string;
            /** Recommendation */
            recommendation?: string | null;
            /**
             * Reference
             * @description Specification or documentation URL.
             */
            reference?: string | null;
            /** Title */
            title: string;
            /**
             * Weight
             * @description Points available when the rule is applicable.
             */
            weight: number;
        };
        /** SecurityScore */
        SecurityScore: {
            /** Applied Caps */
            applied_caps?: components["schemas"]["AppliedCap"][];
            band: components["schemas"]["PostureBand"];
            /** Band Phrase */
            band_phrase: string;
            /**
             * Disclaimer
             * @default This is a passive assessment of externally observable configuration for a single page at a single point in time. It does not evaluate application logic, server-side controls, dependencies, or data handling, and it cannot establish that a site is secure or insecure.
             */
            disclaimer: string;
            /** Excluded Rules */
            excluded_rules?: components["schemas"]["ExcludedRule"][];
            /**
             * Label
             * @default Observable Security Posture
             */
            label: string;
            /** Methodology Version */
            methodology_version: string;
            /** Percentage */
            percentage: number;
            /**
             * Points Applicable
             * @description Sum of weights for evaluated rules only; excluded rules are not counted.
             */
            points_applicable: number;
            /** Points Awarded */
            points_awarded: number;
            /** Rules */
            rules?: components["schemas"]["SecurityRuleResult"][];
        };
        /** StageCapability */
        StageCapability: {
            /** Implemented */
            implemented: boolean;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Optional */
            optional: boolean;
            /** Weight */
            weight: number;
        };
        /**
         * StageKey
         * @description Collection and analysis stages, in execution order.
         * @enum {string}
         */
        StageKey: "validate" | "dns" | "robots" | "http_probe" | "tls" | "browser_launch" | "navigate" | "dom_capture" | "runtime_capture" | "style_capture" | "perf_capture" | "network_capture" | "a11y_capture" | "responsive_probe" | "screenshot" | "analyze" | "research" | "inference" | "assemble";
        /**
         * StageProgress
         * @description Progress derived from stages that actually completed.
         *
         *     There is no interpolation and no time-based estimate here on purpose: the requirement
         *     is honest progress, and the simplest way to guarantee it is to have no mechanism
         *     capable of faking it.
         */
        StageProgress: {
            /**
             * Completed Weight
             * @default 0
             */
            completed_weight: number;
            current_stage?: components["schemas"]["StageKey"] | null;
            /** Current Stage Label */
            current_stage_label?: string | null;
            /**
             * Stages Completed
             * @default 0
             */
            stages_completed: number;
            /**
             * Stages Total
             * @default 0
             */
            stages_total: number;
            /**
             * Total Weight
             * @default 0
             */
            total_weight: number;
        };
        /** StageRun */
        StageRun: {
            /** Duration Ms */
            duration_ms?: number | null;
            error_code?: components["schemas"]["ErrorCode"] | null;
            /** Error Detail */
            error_detail?: string | null;
            key: components["schemas"]["StageKey"];
            /** Label */
            label: string;
            /** Skip Reason */
            skip_reason?: string | null;
            /** Started At */
            started_at?: string | null;
            status: components["schemas"]["StageStatus"];
        };
        /**
         * StageStatus
         * @enum {string}
         */
        StageStatus: "pending" | "running" | "completed" | "failed" | "skipped";
        /** StructuredDataBlock */
        StructuredDataBlock: {
            /** Format */
            format: string;
            /** Parse Error */
            parse_error?: string | null;
            /** Raw Length */
            raw_length?: number | null;
            /** Types */
            types?: string[];
            /** Valid */
            valid: boolean;
        };
        /** SummarizeRequest */
        SummarizeRequest: {
            /** Result Data */
            result_data?: {
                [key: string]: unknown;
            } | null;
            /** Scan Id */
            scan_id?: string | null;
        };
        /** SummarizeResponse */
        SummarizeResponse: {
            /** Available */
            available: boolean;
            /**
             * Disclaimer
             * @default This summary is AI-generated from verified analysis findings. It does not introduce new detections or modify factual values.
             */
            disclaimer: string;
            /** Model */
            model?: string | null;
            /** Summary */
            summary?: string | null;
        };
        /**
         * TargetInfo
         * @description What we ended up analyzing, which is not always what was requested.
         */
        TargetInfo: {
            /** Document Title */
            document_title?: string | null;
            /** Final Url */
            final_url?: string | null;
            /** Host */
            host: string;
            /** Http Status */
            http_status?: number | null;
            /** Normalized Url */
            normalized_url: string;
            /** Port */
            port: number;
            /** Redirect Chain */
            redirect_chain?: components["schemas"]["RedirectHop"][];
            /** Requested Url */
            requested_url: string;
            /** Resolved Ips */
            resolved_ips?: string[];
            robots?: components["schemas"]["RobotsObservation"] | null;
            /** Scheme */
            scheme: string;
        };
        /**
         * TechnologyPayload
         * @description Consolidated technology + architecture + network + performance + SEO data.
         */
        TechnologyPayload: {
            /** By Domain */
            by_domain?: components["schemas"]["DomainSummary"][];
            indexability?: components["schemas"]["IndexabilityObservation"] | null;
            metadata?: components["schemas"]["MetadataObservation"] | null;
            /**
             * Network Cap Hit
             * @default false
             */
            network_cap_hit: boolean;
            /** Products */
            products?: components["schemas"]["DetectedProduct"][];
            /** Requests */
            requests?: components["schemas"]["NetworkRequestRecord"][];
            /** Static Vs Rendered Element Delta */
            static_vs_rendered_element_delta?: number | null;
            /** Structured Data */
            structured_data?: components["schemas"]["StructuredDataBlock"][];
            timings?: components["schemas"]["PerformanceObservation"] | null;
        };
        /**
         * TrafficPayload
         * @description Traffic and popularity intelligence from external public data sources.
         */
        TrafficPayload: {
            /**
             * Provider Available
             * @default false
             */
            provider_available: boolean;
            /**
             * Provider Name
             * @description Which traffic provider was used, or None if unavailable.
             */
            provider_name?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Viewport */
        Viewport: {
            /**
             * Height
             * @default 900
             */
            height: number;
            /**
             * Width
             * @default 1440
             */
            width: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    explain_api_v1_ai_explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description No AI provider is configured. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    summarize_api_v1_ai_summarize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummarizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummarizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_api_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    create_scan_api_v1_scans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_api_v1_scans__scan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanJobState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scan_api_v1_scans__scan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_events_api_v1_scans__scan_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_result_api_v1_scans__scan_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description The scan has not finished yet. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The result was released after the retention window. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
