/**
 * Blocks shared by every report file.
 *
 * Three of these encode product promises rather than formatting preferences:
 *
 * - `runContextBlock` - measurements are meaningless without the conditions they were taken under.
 * - `findingsBlock` - status is spelled out in words, and `confidence` is never printed beside a
 *   claim (docs/blueprint/decisions.md D5).
 * - `interpretationsBlock` - subjective readings live in their own fenced section, citing the
 *   findings they came from, so they can never be mistaken for observations.
 */
import { formatDuration, formatTimestamp } from '@/lib/format/values';
import { findingStatusLabel, isAsserted } from '@/lib/format/status';
import type {
  AnalysisResult,
  Finding,
  Interpretation,
  Section,
  SectionKey,
} from '@/types/analysis';
import { findingStatusToVerdict, verdictLabel } from '@/types/analysis';

import {
  bullets,
  cell,
  codeBlock,
  detailsBlock,
  heading,
  keyValueTable,
  section as join,
  table,
} from './kit';

export const GENERATOR = 'WebLens report generator 2.0';

export const STANDING_DISCLAIMER =
  'WebLens observes what a normal visit to a public URL reveals. It is passive: no forms were ' +
  'submitted, no authentication was attempted, and no access controls were tested. Findings ' +
  'describe one page at one point in time.';

export interface RenderContext {
  result: AnalysisResult;
  sectionKey: SectionKey;
  section: Section;
  options: RenderOptions;
}

export interface RenderOptions {
  includeEvidence: boolean;
  maxEvidencePerFinding: number;
}

export const DEFAULT_RENDER_OPTIONS: RenderOptions = {
  includeEvidence: true,
  maxEvidencePerFinding: 4,
};

export function frontMatter(result: AnalysisResult, title: string): string {
  const scan = result.scan;
  return join(
    heading(1, `${title} — ${result.target.host}`),
    keyValueTable([
      ['Requested URL', result.target.requested_url],
      ['Normalized URL', result.target.normalized_url],
      ['Final URL', result.target.final_url],
      ['HTTP status', result.target.http_status],
      ['Scan id', scan.scan_id],
      ['Scan status', scan.status],
      ['Started', formatTimestamp(scan.started_at)],
      ['Finished', formatTimestamp(scan.finished_at)],
      ['Duration', formatDuration(scan.duration_ms)],
      ['Engine version', scan.engine_version],
      ['Schema version', result.schema_version],
      ['Generated by', GENERATOR],
      ['Generated at', formatTimestamp(new Date().toISOString())],
    ]),
  );
}

export function runContextBlock(result: AnalysisResult): string {
  const context = result.scan.run_context;
  if (!context) {
    return join(
      heading(2, 'Run context'),
      '_Not recorded for this scan, so measurements below cannot be reproduced exactly._',
    );
  }
  return join(
    heading(2, 'Run context'),
    'Every measurement in this report was taken under these conditions.',
    keyValueTable([
      ['Collection mode', context.collection_mode],
      ['Browser', context.browser_name ? `${context.browser_name} ${context.browser_version ?? ''}`.trim() : 'not used'],
      ['Viewport', `${context.viewport.width}×${context.viewport.height} @ ${context.device_scale_factor}x`],
      ['Wait strategy', context.wait_strategy],
      ['Settle reached', context.settle_reached === null || context.settle_reached === undefined ? 'not applicable' : String(context.settle_reached)],
      ['Network throttling', context.network_throttling],
      ['CPU throttling', context.cpu_throttling],
      ['Locale / timezone', `${context.locale} / ${context.timezone}`],
      ['User agent', context.user_agent],
    ]),
  );
}

export function sectionStatusBlock(ctx: RenderContext): string {
  const meta = ctx.section.meta;
  const rows = meta.analyzers.map((run) => [
    run.id,
    run.version,
    run.status,
    run.duration_ms === null || run.duration_ms === undefined ? '—' : formatDuration(run.duration_ms),
    run.error_code ?? '—',
    run.error_detail ?? run.missing_evidence.join(', ') ?? '—',
  ]);

  return join(
    heading(2, 'Section status'),
    keyValueTable([
      ['Status', meta.status],
      ['Reason', meta.unavailable_reason],
    ]),
    heading(3, 'Analyzers'),
    table(['Analyzer', 'Version', 'Outcome', 'Duration', 'Error code', 'Detail'], rows),
  );
}

/** Rendered when a section produced nothing, so a partial scan documents itself. */
export function unavailableBlock(ctx: RenderContext): string {
  const meta = ctx.section.meta;
  const explanation =
    meta.status === 'not_implemented'
      ? 'No analyzer for this section ships in this build of WebLens yet. Nothing about the target was inferred in its place.'
      : 'This section could not be produced for this scan.';
  return join(
    heading(2, 'No findings available'),
    explanation,
    meta.unavailable_reason ? `**Reason:** ${meta.unavailable_reason}` : null,
  );
}

export function findingsBlock(ctx: RenderContext): string {
  const findings = ctx.section.findings;
  if (findings.length === 0) return '';

  const byCategory = new Map<string, Finding[]>();
  for (const finding of [...findings].sort(compareFindings)) {
    const group = byCategory.get(finding.category) ?? [];
    group.push(finding);
    byCategory.set(finding.category, group);
  }

  const blocks = [...byCategory.entries()].map(([category, group]) =>
    join(
      heading(3, humanize(category)),
      table(
        ['Finding', 'Status', 'Value', 'Notes'],
        group.map((finding) => [
          finding.name,
          findingStatusLabel(finding.status),
          renderValue(finding),
          finding.reason ?? '',
        ]),
      ),
      ctx.options.includeEvidence ? evidenceBlock(group, ctx.options) : '',
    ),
  );

  return join(
    heading(2, 'Findings'),
    statusLegend(),
    ...blocks,
  );
}

function statusLegend(): string {
  return bullets([
    '**Verified** — directly observed in the collected evidence.',
    '**Strongly inferred** — supported by multiple strong signals, but not directly confirmed.',
    '**Inferred** — derived from indirect signals; the signals are listed with the finding.',
    '**AI inferred** — an AI-generated hypothesis grounded in listed evidence; never a verified fact.',
    '**Not detected** — evidence was collected and the signal was absent. This is not the same as "not used".',
    '**Not determinable** — the property cannot be observed from outside the site.',
    '**Unable to verify** — the evidence needed for the check was unavailable in this scan.',
  ]);
}

function evidenceBlock(findings: Finding[], options: RenderOptions): string {
  const asserted = findings.filter(
    (finding) => finding.evidence.length > 0 && isAsserted(finding),
  );
  if (asserted.length === 0) return '';

  const body = asserted
    .map((finding) => {
      const items = finding.evidence.slice(0, options.maxEvidencePerFinding).map((ref) => {
        const location = ref.location ? ` — ${ref.location}` : '';
        const excerpt = ref.excerpt ? `\n${codeBlock(ref.excerpt)}` : '';
        return `- \`${ref.source}\` (${ref.kind})${location}${excerpt}`;
      });
      const omitted =
        finding.evidence.length > options.maxEvidencePerFinding
          ? `\n- _…${finding.evidence.length - options.maxEvidencePerFinding} further observation(s) omitted._`
          : '';
      return `**${finding.name}** (\`${finding.id}\`)\n${items.join('\n')}${omitted}`;
    })
    .join('\n\n');

  return detailsBlock('Observed evidence', body);
}

export function interpretationsBlock(interpretations: Interpretation[]): string {
  if (interpretations.length === 0) return '';
  return join(
    heading(2, 'Interpretation'),
    '> The statements below are readings of the measured values above, not observations. They are ' +
      'presented separately because they are judgements, and each cites the findings it derives from.',
    ...interpretations.map((item) =>
      join(
        `**${item.statement}**`,
        bullets([`Derived from: ${item.basis.map((id) => `\`${id}\``).join(', ')}`, item.caveat]),
      ),
    ),
  );
}

export function limitationsBlock(ctx: RenderContext): string {
  const sectionLimits = ctx.section.meta.limitations;
  const findingLimits = [
    ...new Set(ctx.section.findings.flatMap((finding) => finding.limitations)),
  ].filter((limit) => !sectionLimits.includes(limit));
  const scanLimits = ctx.result.limitations;

  if (sectionLimits.length + findingLimits.length + scanLimits.length === 0) return '';

  return join(
    heading(2, 'Limitations'),
    sectionLimits.length > 0 ? join(heading(3, 'This section'), bullets(sectionLimits)) : '',
    findingLimits.length > 0 ? join(heading(3, 'Specific findings'), bullets(findingLimits)) : '',
    scanLimits.length > 0 ? join(heading(3, 'This scan'), bullets(scanLimits)) : '',
  );
}

export function scanErrorsBlock(result: AnalysisResult, sectionKey: SectionKey): string {
  const relevant = result.errors.filter((error) => error.subject.startsWith(`${sectionKey}.`));
  if (relevant.length === 0) return '';
  return join(
    heading(2, 'Errors during this section'),
    table(
      ['Subject', 'Scope', 'Code', 'Message', 'Detail'],
      relevant.map((error) => [error.subject, error.scope, error.code, error.message, error.detail]),
    ),
  );
}

export function footer(): string {
  return join('---', `_${STANDING_DISCLAIMER}_`);
}

/**
 * Standard document assembly shared by every renderer.
 *
 * `extra` blocks are always rendered, even when the section produced no findings. Several of them
 * describe the scan rather than the section - run context, target and redirect chain, the reason no
 * security score exists - and suppressing those would make an unavailable section's report less
 * informative exactly when the reader most needs the context. Blocks derived from section data
 * return empty strings of their own accord when there is nothing to show.
 */
export function standardDocument(ctx: RenderContext, title: string, ...extra: string[]): string {
  const renderable = ctx.section.meta.status === 'complete' || ctx.section.meta.status === 'partial';
  return join(
    frontMatter(ctx.result, title),
    sectionStatusBlock(ctx),
    renderable ? '' : unavailableBlock(ctx),
    ...extra,
    renderable ? findingsBlock(ctx) : '',
    renderable ? interpretationsBlock(ctx.section.interpretations) : '',
    scanErrorsBlock(ctx.result, ctx.sectionKey),
    limitationsBlock(ctx),
    footer(),
  );
}

function renderValue(finding: Finding): string {
  if (finding.value !== null && finding.value !== undefined) {
    const base = typeof finding.value === 'boolean' ? (finding.value ? 'yes' : 'no') : String(finding.value);
    return finding.unit && finding.unit !== 'count' ? `${base} ${finding.unit}` : base;
  }
  if (finding.values.length > 0) return finding.values.map(cell).join(', ');
  return '—';
}

function compareFindings(a: Finding, b: Finding): number {
  return a.category.localeCompare(b.category) || a.id.localeCompare(b.id);
}

export function humanize(value: string): string {
  return value
    .replace(/[_-]+/g, ' ')
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

// --- Evidence quality and AI verdict blocks for the new report format ---

/**
 * Evidence quality summary block for each section.
 * Shows the quality gate assessment if available.
 */
export function evidenceQualityBlock(result: AnalysisResult, sectionKey: SectionKey): string {
  const quality = result.quality;
  if (!quality) return '';

  const sectionQuality = quality.sections[sectionKey];
  if (!sectionQuality) return '';

  const aiMode = quality.ai_fallback_available
    ? (quality.ai_fallback_sections.includes(sectionKey) ? 'AI Intelligence recommended' : 'Normal evidence sufficient')
    : 'Normal evidence (AI not configured)';

  return join(
    heading(2, 'Evidence Quality'),
    keyValueTable([
      ['Quality band', humanize(sectionQuality.quality)],
      ['Score', `${sectionQuality.score}/100`],
      ['Analyzers', `${sectionQuality.analyzers_completed}/${sectionQuality.analyzers_total} completed`],
      ['Verified findings', sectionQuality.findings_verified],
      ['Inferred findings', sectionQuality.findings_inferred],
      ['Negative findings', sectionQuality.findings_negative],
      ['Analysis mode', aiMode],
    ]),
    sectionQuality.ai_fallback_recommended
      ? `_${sectionQuality.reason}_`
      : '',
  );
}

/**
 * AI/Research verdicts block for findings that came from AI inference.
 * Only rendered when AI findings exist for the section.
 */
export function aiVerdictBlock(aiFindings: Finding[], title: string): string {
  if (aiFindings.length === 0) {
    return join(
      heading(2, title),
      '_No AI intelligence was applied to this section._',
    );
  }

  const rows = aiFindings.map((finding) => {
    const verdict = verdictLabel(findingStatusToVerdict(finding.status));
    const reasoning = finding.evidence
      .filter((e) => e.kind === 'ai_reasoning')
      .map((e) => e.excerpt)
      .filter(Boolean)
      .join(' ');
    const basis = finding.evidence
      .flatMap((e) => {
        const b = e.detail?.basis;
        return typeof b === 'string' ? b.split(',').map((s: string) => s.trim()) : [];
      })
      .filter(Boolean)
      .slice(0, 5)
      .join(', ');

    return [
      finding.name,
      verdict,
      reasoning?.slice(0, 150) || '—',
      basis || '—',
      finding.limitations.join('; ') || '—',
    ];
  });

  return join(
    heading(2, title),
    'These findings were produced by AI intelligence and are clearly marked as hypotheses. ' +
    'They are based on observable evidence and public research, never fabricated.',
    table(
      ['Claim', 'Verdict', 'Reasoning', 'Basis', 'Limitations'],
      rows,
    ),
  );
}
