"""Observation models that make up :class:`~weblens.domain.evidence.RawEvidence`."""

from weblens.domain.observations.measurement import (
    AxeNode,
    AxeObservation,
    AxeViolation,
    LongTaskEntry,
    NetworkObservation,
    NetworkRequestRecord,
    PerformanceObservation,
)
from weblens.domain.observations.page import (
    ConsoleMessage,
    DomObservation,
    FormObservation,
    HeadingObservation,
    ImageObservation,
    LinkTagObservation,
    MetaTagObservation,
    RuntimeObservation,
    SampleCoverage,
    ScreenshotArtifact,
    ScriptObservation,
    StructuredDataBlock,
    StyleObservation,
    StylePropertyDistribution,
    StyleValueCount,
    ViewportMetrics,
)
from weblens.domain.observations.research import ResearchObservation, ResearchRef
from weblens.domain.observations.transport import (
    CertificateObservation,
    CookieAttributes,
    DnsObservation,
    HeaderEntry,
    HttpHopObservation,
    HttpObservation,
    Observation,
    RobotsObservation,
    TargetObservation,
    TlsObservation,
)

__all__ = [
    "AxeNode",
    "AxeObservation",
    "AxeViolation",
    "CertificateObservation",
    "ConsoleMessage",
    "CookieAttributes",
    "DnsObservation",
    "DomObservation",
    "FormObservation",
    "HeaderEntry",
    "HeadingObservation",
    "HttpHopObservation",
    "HttpObservation",
    "ImageObservation",
    "LinkTagObservation",
    "LongTaskEntry",
    "MetaTagObservation",
    "NetworkObservation",
    "NetworkRequestRecord",
    "Observation",
    "PerformanceObservation",
    "ResearchObservation",
    "ResearchRef",
    "RobotsObservation",
    "RuntimeObservation",
    "SampleCoverage",
    "ScreenshotArtifact",
    "ScriptObservation",
    "StructuredDataBlock",
    "StyleObservation",
    "StylePropertyDistribution",
    "StyleValueCount",
    "TargetObservation",
    "TlsObservation",
    "ViewportMetrics",
]
